### ISSUE TITLE
Arathi Basin

### ISSUE THREAD

**Issue by alphabitnz** [DeadlyBossMods/DBM-PvP#69]
r110-classic

Arathi Basin capture timers have turned into not really "progress" bars but just bars counting into negatives since assault

![image](https://user-images.githubusercontent.com/9102111/105443940-be909a00-5cd1-11eb-9fcf-3ab38d28342c.png)

![image](https://user-images.githubusercontent.com/9102111/105443948-c2242100-5cd1-11eb-8824-75d25abe23c8.png)

**Comment by QartemisT** [comment]
r111 should fix this issue. It was due to a fault timer code while we were attempting to resolve some reported DBT issues. However, since these issues are now fixed in core and this was buggy, I've reverted it :)

**Comment by Werkzs** [comment]
I'm on r111 and did an AV game. Issue still persists 
![Timers](https://user-images.githubusercontent.com/77896944/105612287-fa7a3c80-5d6f-11eb-9874-f0f771b84743.JPG)

**Comment by Werkzs** [comment]
![Version](https://user-images.githubusercontent.com/77896944/105612358-74122a80-5d70-11eb-9619-c96e69b2a6ea.JPG)

**Comment by QartemisT** [comment]
Should be fixed as of r112. Added some better fallback for timers in classic, and made the timers not keeping (So they should never go negative).
